import { ColumnOptions } from 'tui-grid';
import { SHILLION, STOCK_LIST_GRID_COLUMN_NAMES } from '~/constants';
import { convert } from '~/libraries/convert';
import { NumberInput } from './NumberInput';

export const gridColumns: ColumnOptions[] = [
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.MARKET_KIND,
    header: '시장구분',
    filter: 'select',
    valign: 'middle',
    width: 100,
    align: 'left',
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.CORPERATE_NAME,
    header: '회사명',
    filter: 'select',
    valign: 'middle',
    align: 'left',
  },
  { name: STOCK_LIST_GRID_COLUMN_NAMES.NAVER_LINK, width: 100, header: '네이버주식', align: 'center' },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.TODAY_CLOSE_PRICE,
    header: '종가',
    valign: 'middle',
    sortable: true,
    width: 100,
    align: 'right',
    formatter: ({ value }) => `${convert.getSeparatorStringFromFormatterValue(value)}원`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.CHANGE_PRICE,
    header: '전일비',
    valign: 'middle',
    sortable: true,
    width: 90,
    align: 'right',
    formatter: ({ value }) => `${convert.getSeparatorStringFromFormatterValue(value)}원`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.CHANGE_PERCENT,
    header: '1D등락률',
    valign: 'middle',
    sortable: true,
    width: 80,
    align: 'right',
    formatter: ({ value }) => `${convert.getSeparatorStringFromFormatterValue(value)}%`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.CHANGE_PERCENT_FOR_A_WEEK,
    header: '1W등락률',
    valign: 'middle',
    sortable: true,
    width: 80,
    defaultValue: 0,
    align: 'right',
    formatter: ({ value }) => `${convert.getSeparatorStringFromFormatterValue(value)}%`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.CHANGE_PERCENT_FOR_A_MONTH,
    header: '1M등락률',
    valign: 'middle',
    sortable: true,
    width: 80,
    defaultValue: 0,
    align: 'right',
    formatter: ({ value }) => `${convert.getSeparatorStringFromFormatterValue(value)}%`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.CHANGE_PERCENT_FOR_THREE_MONTH,
    header: '3M등락률',
    valign: 'middle',
    sortable: true,
    width: 80,
    defaultValue: 0,
    align: 'right',
    formatter: ({ value }) => `${convert.getSeparatorStringFromFormatterValue(value)}%`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.PROFIT21,
    header: '순이익21',
    valign: 'middle',
    sortable: true,
    width: 100,
    defaultValue: 0,
    align: 'right',
    editor: {
      type: NumberInput,
      options: {
        maxLength: 7,
      },
    },
    formatter: ({ value }) => convert.getKoreanWonFromFormatterValue(value, SHILLION),
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.PROFIT22,
    header: '순이익22',
    valign: 'middle',
    sortable: true,
    width: 100,
    defaultValue: 0,
    align: 'right',
    editor: {
      type: NumberInput,
      options: {
        maxLength: 7,
      },
    },
    formatter: ({ value }) => convert.getKoreanWonFromFormatterValue(value, SHILLION),
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.PROFIT23,
    header: '순이익23',
    valign: 'middle',
    sortable: true,
    width: 100,
    defaultValue: 0,
    align: 'right',
    editor: {
      type: NumberInput,
      options: {
        maxLength: 7,
      },
    },
    formatter: ({ value }) => convert.getKoreanWonFromFormatterValue(value, SHILLION),
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.PER21,
    header: 'PER21(배)',
    valign: 'middle',
    sortable: true,
    filter: {
      type: 'number',
      operator: 'OR',
      showApplyBtn: true,
      showClearBtn: true,
    },
    width: 110,
    defaultValue: 0,
    align: 'right',
    formatter: ({ value }) => Number(value).toFixed(2),
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.PER22,
    header: 'PER22(배)',
    valign: 'middle',
    sortable: true,
    filter: {
      type: 'number',
      operator: 'OR',
      showApplyBtn: true,
      showClearBtn: true,
    },
    width: 110,
    defaultValue: 0,
    align: 'right',
    formatter: ({ value }) => Number(value).toFixed(2),
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.PER23,
    header: 'PER23(배)',
    valign: 'middle',
    sortable: true,
    filter: {
      type: 'number',
      operator: 'OR',
      showApplyBtn: true,
      showClearBtn: true,
    },
    width: 110,
    defaultValue: 0,
    align: 'right',
    formatter: ({ value }) => Number(value).toFixed(2),
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.RATE_OF_GROWTH,
    header: '성장률(%)',
    valign: 'middle',
    sortable: true,
    filter: {
      type: 'number',
      operator: 'OR',
      showApplyBtn: true,
      showClearBtn: true,
    },
    width: 110,
    defaultValue: 0,
    align: 'right',
    formatter: ({ value }) => `${Math.round(Number(value)).toFixed(0)}%`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.TODAY_OPEN_PRICE,
    header: '시초가',
    valign: 'middle',
    width: 100,
    align: 'right',
    formatter: ({ value }) => `${convert.getSeparatorStringFromFormatterValue(value)}원`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.TODAY_HIGH_PRICE,
    header: '고가',
    valign: 'middle',
    width: 100,
    align: 'right',
    formatter: ({ value }) => `${convert.getSeparatorStringFromFormatterValue(value)}원`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.TODAY_LOW_PRICE,
    header: '저가',
    valign: 'middle',
    width: 100,
    align: 'right',
    formatter: ({ value }) => `${convert.getSeparatorStringFromFormatterValue(value)}원`,
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.VOLUME,
    header: '거래량',
    valign: 'middle',
    sortable: true,
    width: 100,
    align: 'right',
    formatter: ({ value }) => convert.getSeparatorStringFromFormatterValue(value),
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.SHARES_OUTSTANDING,
    header: '발행주식수',
    valign: 'middle',
    width: 120,
    align: 'right',
    formatter: ({ value }) => convert.getSeparatorStringFromFormatterValue(value),
  },
  {
    name: STOCK_LIST_GRID_COLUMN_NAMES.MARKET_CAPITALIZATION,
    header: '시가총액',
    valign: 'middle',
    sortable: true,
    sortingType: 'desc',
    width: 110,
    align: 'right',
    formatter: ({ value }) => convert.getKoreanWonFromFormatterValue(value),
  },
];
